In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

# Data Profile

In [6]:
import pandas as pd 
A=pd.read_csv("C:/Users/Dell/Downloads/Google_Stock_Price_Train.csv")

In [7]:
A.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [8]:
A.tail()

Date    Open    High     Low   Close     Volume
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

# Missing Data

In [9]:
A.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

# Get stock opening price

In [10]:
trd = A[["Open"]].values

In [11]:
trd

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

# MinmaxScaler

In [12]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit_transform(trd)

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create Data for training and testing

In [13]:
trd.shape

(1258, 1)

In [28]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])

In [29]:
import numpy as np

In [30]:
type(xtrain)

list

In [31]:
type(ytrain)

list

# Converting into Array

In [32]:
xtr = np.array(xtrain)

In [33]:
xtr.shape

(1208, 50, 1)

In [34]:
ytr = np.array(ytrain)

In [35]:
ytr.shape

(1208, 1, 1)

# Create a NN

In [36]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout

In [37]:
nn = Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dense(1))

In [39]:
nn.compile(optimizer="adam",loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=60)

Epoch 1/60
38/38 [==============================] - 7s 64ms/step - loss: 261780.5625
Epoch 2/60
38/38 [==============================] - 2s 61ms/step - loss: 258066.2969
Epoch 3/60
38/38 [==============================] - 2s 61ms/step - loss: 254426.2969
Epoch 4/60
38/38 [==============================] - 2s 61ms/step - loss: 250695.5000
Epoch 5/60
38/38 [==============================] - 2s 61ms/step - loss: 246968.6562
Epoch 6/60
38/38 [==============================] - 3s 69ms/step - loss: 243299.6875
Epoch 7/60
38/38 [==============================] - 2s 61ms/step - loss: 239746.7344
Epoch 8/60
38/38 [==============================] - 2s 60ms/step - loss: 236249.4062
Epoch 9/60
38/38 [==============================] - 2s 61ms/step - loss: 232808.5312
Epoch 10/60
38/38 [==============================] - 2s 61ms/step - loss: 229406.0469
Epoch 11/60
38/38 [==============================] - 2s 62ms/step - loss: 226054.1250
Epoch 12/60
38/38 [==============================] - 2s 64ms/st

# Import Test Dataset

In [40]:
tsd = pd.read_csv("C:/Users/Dell/Downloads/Google_Stock_Price_Test.csv")

In [42]:
tsd.head()

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2  1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3  1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4  1/9/2017  806.40  809.97  802.83  806.65  1,272,400

In [43]:
tsd.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [44]:
tsd[["Open"]]

Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [45]:
tsd.shape

(20, 6)

In [46]:
Q = pd.concat([A,tsd])
Q.index = range(0,1278)

In [47]:
Q = Q[["Open"]].values

In [48]:
xtest = []
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [49]:
xts = np.array(xtest)

In [50]:
xts.shape

(19, 50, 1)

In [51]:
tsd

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Prediction

In [54]:
nn.predict(xts)

array([[[198.15033],
        [250.27936],
        [258.26047],
        [259.36002],
        [259.5092 ],
        [259.5294 ],
        [259.5321 ],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.53253],
        [259.